server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: npminhtri.be@gmail.com
    password: cfubhnaxnbdzsnta
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

jwt:
  secret: "4D2224546D8817FCFAB272A7FC9F9"
  access-minutes: 30
  refresh-days: 7

app:
  base-url: http://localhost:8080
  verify:
    expiry-minutes: 30
