server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: npminhtri.be@gmail.com
    password: cfubhnaxnbdzsnta
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000

app:
  verification-url: "http://gateway-service:8080/auth/verify"

jwt:
  secret: "UCIafMmHwgsJKIgg4xVAL/eOvR3ZXD/ZnYE9AfMaMQg="
  access-minutes: 30
  refresh-days: 7

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registryFetchIntervalSeconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}