server:
  port: 8761

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    discovery:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
